export { Dashboard } from './Dashboard';
export { WindowsPage } from './WindowsPage';
export { OfficePage } from './OfficePage';
export { ExtraAppsPage } from './ExtraAppsPage';
export { UtilitiesPage } from './UtilitiesPage';
export { NetworkPage } from './NetworkPage';
export { SettingsPage } from './SettingsPage';
export { UninstallerPage } from './UninstallerPage';
export { InstallPage } from './InstallPage';
